# Generated by Django 3.0.6 on 2020-06-10 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-schedule']},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.FloatField(default=0)),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Workdays')),
            ],
            options={
                'ordering': ['-workday'],
            },
        ),
    ]
