# Generated by Django 3.0.6 on 2020-06-12 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20200610_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Person')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
