# Generated by Django 3.0.6 on 2020-06-13 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_waitinglist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitinglist',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='waitinglist',
            name='date',
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
