# Generated by Django 3.0.6 on 2020-06-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20200613_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitinglist',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='person',
            name='bmi',
        ),
    ]
