# Generated by Django 3.0.6 on 2020-06-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20200613_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bmi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='smoker',
            field=models.BooleanField(default=0),
        ),
    ]
