# Generated by Django 3.0.6 on 2020-06-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_auto_20200613_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdays',
            name='dosage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.Schedule'),
        ),
    ]
