# Generated by Django 3.0.6 on 2020-07-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_auto_20200628_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='accomplished',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
