# Generated by Django 3.0.6 on 2020-07-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_appointment_accomplished'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
